"""Public API for the LLM service layer."""

from .config import (
    AnthropicProviderSettings,
    EmbeddingSettings,
    GeminiProviderSettings,
    GrokProviderSettings,
    LLMSettings,
    LMStudioProviderSettings,
    OpenAIProviderSettings,
    OpenRouterProviderSettings,
)
from .errors import (
    LLMConfigurationError,
    LLMError,
    ProviderAuthenticationError,
    ProviderBadRequestError,
    ProviderNotFoundError,
    ProviderRateLimitError,
    ProviderResponseError,
    ProviderTemporaryError,
    ProviderTimeoutError,
    StreamProtocolError,
    ToolCallValidationError,
    UnsupportedCapabilityError,
)
from .protocols import LLMProvider, ProviderCapabilities
from .service import LLMService, ProviderRegistry
from .types import (
    DoneEvent,
    EmbeddingRequest,
    EmbeddingResponse,
    ImagePart,
    LLMMessage,
    LLMRequest,
    LLMResponse,
    LLMRole,
    LLMStreamEvent,
    LLMUsage,
    TextDeltaEvent,
    TextPart,
    ToolCall,
    ToolCallDeltaEvent,
    ToolChoice,
    ToolChoiceMode,
    ToolDefinition,
    ToolResultPart,
    UsageDeltaEvent,
)

__all__ = [
    "DoneEvent",
    "EmbeddingRequest",
    "EmbeddingResponse",
    "EmbeddingSettings",
    "ImagePart",
    "LLMConfigurationError",
    "LLMError",
    "LLMMessage",
    "LLMProvider",
    "LLMRequest",
    "LLMResponse",
    "LLMRole",
    "LLMService",
    "LLMSettings",
    "LLMStreamEvent",
    "LLMUsage",
    "OpenAIProviderSettings",
    "AnthropicProviderSettings",
    "GeminiProviderSettings",
    "GrokProviderSettings",
    "LMStudioProviderSettings",
    "OpenRouterProviderSettings",
    "ProviderAuthenticationError",
    "ProviderBadRequestError",
    "ProviderCapabilities",
    "ProviderNotFoundError",
    "ProviderRateLimitError",
    "ProviderRegistry",
    "ProviderResponseError",
    "ProviderTemporaryError",
    "ProviderTimeoutError",
    "StreamProtocolError",
    "TextDeltaEvent",
    "TextPart",
    "ToolCall",
    "ToolCallDeltaEvent",
    "ToolCallValidationError",
    "ToolChoice",
    "ToolChoiceMode",
    "ToolDefinition",
    "ToolResultPart",
    "UnsupportedCapabilityError",
    "UsageDeltaEvent",
]
