"""Internal defaults for email tool limits and timeouts."""

DEFAULT_EMAIL_TIMEOUT_SECONDS = 30.0
DEFAULT_EMAIL_MAX_SUBJECT_CHARS = 200
DEFAULT_EMAIL_MAX_BODY_CHARS = 20_000
DEFAULT_EMAIL_MAX_ATTACHMENT_COUNT = 10
DEFAULT_EMAIL_MAX_TOTAL_ATTACHMENT_BYTES = 20 * 1024 * 1024
