"""Non-secret project runtime settings.

Secrets are loaded separately from Docker secret files.
"""

from __future__ import annotations

from typing import Final

# Gateway websocket runtime.
JARVIS_GATEWAY_HOST: Final = "127.0.0.1"
JARVIS_GATEWAY_PORT: Final = 8080
JARVIS_GATEWAY_WS_PATH: Final = "/ws"
JARVIS_GATEWAY_MAX_MESSAGE_CHARS: Final = 32_000

# Core workspace paths.
AGENT_WORKSPACE: Final[str | None] = "/workspace" # container path
JARVIS_TRANSCRIPT_ARCHIVE_DIR: Final[str | None] = (
    f"{AGENT_WORKSPACE}/archive/transcripts" if AGENT_WORKSPACE is not None else None
)
JARVIS_IDENTITIES_DIR: Final = "/workspace/identities"
JARVIS_MEMORY_DIR: Final[str | None] = (
    f"{AGENT_WORKSPACE}/memory" if AGENT_WORKSPACE is not None else None
)
JARVIS_MEMORY_INDEX_DIR: Final[str | None] = (
    f"{AGENT_WORKSPACE}/memory/.index" if AGENT_WORKSPACE is not None else None
)

# Tool runtime defaults.
JARVIS_TOOL_BASH_EXECUTABLE: Final = "/bin/bash"
JARVIS_TOOL_BASH_DEFAULT_TIMEOUT_SECONDS: Final = 10.0
JARVIS_TOOL_BASH_MAX_TIMEOUT_SECONDS: Final = 30.0
JARVIS_TOOL_BASH_MAX_OUTPUT_CHARS: Final = 40_000
JARVIS_TOOL_PYTHON_INTERPRETER_VENV: Final = "/opt/jarvis-python-tool-venv"
JARVIS_TOOL_PYTHON_INTERPRETER_ALLOWED_PACKAGES: Final[tuple[str, ...]] = (
    "python-dateutil",
    "pyyaml",
    "pymupdf",
    "pandas",
    "pillow",
    "pydantic",
    "jinja2",
    "rapidfuzz",
    "markdown-it-py",
    "feedparser",
    "openpyxl",
    "python-docx",
    "icalendar",
)
JARVIS_TOOL_PYTHON_INTERPRETER_DEFAULT_TIMEOUT_SECONDS: Final = 10.0
JARVIS_TOOL_PYTHON_INTERPRETER_MAX_TIMEOUT_SECONDS: Final = 30.0
JARVIS_TOOL_PYTHON_INTERPRETER_MAX_OUTPUT_CHARS: Final = 12_000
JARVIS_TOOL_PYTHON_INTERPRETER_MAX_CODE_CHARS: Final = 20_000
JARVIS_TOOL_PYTHON_INTERPRETER_MAX_PATHS: Final = 16
JARVIS_TOOL_PYTHON_INTERPRETER_MAX_STAGED_BYTES: Final = 67_108_864
JARVIS_TOOL_PYTHON_INTERPRETER_MEMORY_LIMIT_BYTES: Final = 536_870_912
JARVIS_TOOL_PYTHON_INTERPRETER_FILE_SIZE_LIMIT_BYTES: Final = 33_554_432
JARVIS_TOOL_MAX_ROUNDS_PER_TURN: Final = 100
JARVIS_TOOL_WEB_SEARCH_RESULT_COUNT: Final = 10
JARVIS_TOOL_WEB_SEARCH_TIMEOUT_SECONDS: Final = 15.0
JARVIS_TOOL_WEB_FETCH_TIMEOUT_SECONDS: Final = 20.0
JARVIS_TOOL_WEB_FETCH_PLAYWRIGHT_TIMEOUT_SECONDS: Final = 20.0
JARVIS_TOOL_WEB_FETCH_MAX_RESPONSE_BYTES: Final = 2_097_152
JARVIS_TOOL_WEB_FETCH_MAX_MARKDOWN_CHARS: Final = 20_000

# Telegram UI runtime.
TELEGRAM_API_BASE_URL: Final = "https://api.telegram.org"
JARVIS_UI_TELEGRAM_ALLOWED_USER_ID: Final[int | None] = None
JARVIS_UI_TELEGRAM_TEMP_DIR: Final[str | None] = (
    f"{AGENT_WORKSPACE}/temp" if AGENT_WORKSPACE is not None else None
)
JARVIS_UI_TELEGRAM_POLL_TIMEOUT_SECONDS: Final = 30
JARVIS_UI_TELEGRAM_POLL_LIMIT: Final = 100
JARVIS_UI_POLL_ERROR_BACKOFF_SECONDS: Final = 2.0
JARVIS_UI_STREAM_DRAFT_MIN_INTERVAL_SECONDS: Final = 1.0
JARVIS_UI_STREAM_DRAFT_MIN_CHARS: Final = 20
JARVIS_UI_TELEGRAM_MAX_MESSAGE_CHARS: Final = 4_096

# Leave unset to derive from the gateway host/port/path settings above.
JARVIS_UI_GATEWAY_WS_BASE_URL: Final[str | None] = None
JARVIS_UI_GATEWAY_CONNECT_TIMEOUT_SECONDS: Final = 15.0

# Core context/session policy.
JARVIS_CONTEXT_WINDOW_TOKENS: Final = 400_000
JARVIS_COMPACT_THRESHOLD_TOKENS: Final = 350_000
JARVIS_COMPACT_RESERVE_OUTPUT_TOKENS: Final = 16_000
JARVIS_COMPACT_RESERVE_OVERHEAD_TOKENS: Final = 10_000
JARVIS_CORE_TIMEZONE: Final = "Europe/Dublin"

# Core LLM routing/runtime.
# The provider chosen here will determine which API key is needed below
# 'openai', 'gemini', 'anthropic', 'openrouter'
JARVIS_LLM_DEFAULT_PROVIDER: Final = "openai"
JARVIS_LLM_TIMEOUT_SECONDS: Final = 60.0
JARVIS_LLM_RETRY_ATTEMPTS: Final = 2
JARVIS_LLM_RETRY_BACKOFF_SECONDS: Final = 0.5

# Global embedding runtime.
JARVIS_EMBEDDING_PROVIDER: Final = "openai"
JARVIS_EMBEDDING_MODEL: Final = "text-embedding-3-small"

# Memory runtime defaults.
JARVIS_MEMORY_MAINTENANCE_LLM_PROVIDER: Final = "openai"
JARVIS_MEMORY_MAINTENANCE_LLM_MODEL: Final = "gpt-5.4-2026-03-05"
JARVIS_MEMORY_MAINTENANCE_LLM_MAX_OUTPUT_TOKENS: Final = 5_000
JARVIS_MEMORY_BOOTSTRAP_MAX_TOKENS: Final = 5_000
JARVIS_MEMORY_CORE_BOOTSTRAP_MAX_TOKENS: Final = 2_500
JARVIS_MEMORY_ONGOING_BOOTSTRAP_MAX_TOKENS: Final = 2_500
JARVIS_MEMORY_SEARCH_DEFAULT_TOP_K: Final = 8
JARVIS_MEMORY_DAILY_LOOKBACK_DAYS: Final = 30
JARVIS_MEMORY_ENABLE_REFLECTION: Final = True
JARVIS_MEMORY_ENABLE_AUTO_APPLY_CORE: Final = True
JARVIS_MEMORY_ENABLE_AUTO_APPLY_ONGOING: Final = True
JARVIS_MEMORY_GRAPH_DEFAULT_EXPAND: Final = 1
JARVIS_MEMORY_LEXICAL_CANDIDATE_COUNT: Final = 30
JARVIS_MEMORY_SEMANTIC_CANDIDATE_COUNT: Final = 30
JARVIS_MEMORY_GRAPH_CANDIDATE_COUNT: Final = 20
JARVIS_MEMORY_HYBRID_RESULT_COUNT: Final = 8

# OpenAI provider defaults.
JARVIS_OPENAI_CHAT_MODEL: Final = "gpt-5.4-2026-03-05"
JARVIS_OPENAI_TEMPERATURE: Final = 1.0
JARVIS_OPENAI_MAX_OUTPUT_TOKENS: Final = 64_000
JARVIS_OPENAI_REASONING_EFFORT: Final = "low"
JARVIS_OPENAI_REASONING_SUMMARY: Final[str | None] = None
JARVIS_OPENAI_TEXT_VERBOSITY: Final[str | None] = None

# Anthropic provider defaults.
JARVIS_ANTHROPIC_CHAT_MODEL: Final = "claude-sonnet-4-6"
JARVIS_ANTHROPIC_TEMPERATURE: Final = 1.0
JARVIS_ANTHROPIC_MAX_OUTPUT_TOKENS: Final = 32_000
JARVIS_ANTHROPIC_THINKING_MODE: Final = "adaptive"
JARVIS_ANTHROPIC_EFFORT: Final = "medium"
JARVIS_ANTHROPIC_THINKING_BUDGET_TOKENS: Final[int | None] = None

# Gemini provider defaults.
JARVIS_GEMINI_CHAT_MODEL: Final = "gemini-3.1-pro-preview"
JARVIS_GEMINI_TEMPERATURE: Final = 1.0
JARVIS_GEMINI_MAX_OUTPUT_TOKENS: Final = 64_000
JARVIS_GEMINI_THINKING_LEVEL: Final = "medium"
JARVIS_GEMINI_THINKING_BUDGET: Final[int | None] = None

# OpenRouter provider defaults.
JARVIS_OPENROUTER_CHAT_MODEL: Final = "moonshotai/kimi-k2.5"
OPENROUTER_APP_NAME: Final = "Jarvis"
JARVIS_OPENROUTER_TEMPERATURE: Final = 0.8
JARVIS_OPENROUTER_MAX_OUTPUT_TOKENS: Final = 10_000
